name: run

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
          java-version: '17'
          distribution: 'temurin'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

        - name: Run tests
          run: ./gradlew test
